repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files

  # clang-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        types_or: [c, c++]

  # clang-tidy
  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy
        args: [--build-dir=build]
        language: system
        types_or: [c, c++]

  # CMake formatting and linting
  - repo: https://github.com/BlankSpruce/gersemi-pre-commit
    rev: 0.27.2
    hooks:
    - id: gersemi
      args: [-i, --no-warn-about-unknown-commands]

  # ruff formatter (analogous to clang-format)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff-format
        args: [--config, python/ruff.toml]
        types_or: [python, pyi]

  # ruff linter (analogous to clang-tidy)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        args: [--config, python/ruff.toml, --fix]
        types_or: [python, pyi]

  # mypy (static type checking)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--config-file, python/mypy.ini]
        types_or: [python, pyi]
